baseURL = "http://code.fitness/"
languageCode = "en"
title = "code.fitness"
theme = "angels-ladder"
uglyurls = true

[params]
  subtitle = "Good code requires care."
  github = "https://github.com/epsitec"
  profile = "/images/profile.png"
  copyright = "Copyright © 2015-2025, Pierre Arnaud; all rights reserved."
  analytics = "UA-446301-3"
